-- Compressed one-statement-per-line version of supabase-rls-core-hardening.sql
-- Paste the entire file into a fresh Supabase SQL editor tab and run with no selection.
create or replace function public.app_is_staff() returns boolean language sql stable security definer set search_path = public as $$ select exists ( select 1 from public.profiles p where p.id = auth.uid() and p.role in ('trainer', 'admin') ); $$;
create or replace function public.app_owns_client(target_client_id uuid) returns boolean language sql stable security definer set search_path = public as $$ select exists ( select 1 from public.clients c where c.id = target_client_id and c.profile_id = auth.uid() ); $$;
revoke all on function public.app_is_staff() from public;
grant execute on function public.app_is_staff() to authenticated;
revoke all on function public.app_owns_client(uuid) from public;
grant execute on function public.app_owns_client(uuid) to authenticated;
drop policy if exists "Trainers can manage profiles" on public.profiles;
drop policy if exists "Clients can view own profile" on public.profiles;
drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Staff can view profiles" on public.profiles;
drop policy if exists "Users can update own profile display fields" on public.profiles;
drop policy if exists "Staff can update profile display fields" on public.profiles;
create policy "Users can view own profile" on public.profiles for select to authenticated using (id = auth.uid());
create policy "Staff can view profiles" on public.profiles for select to authenticated using (public.app_is_staff());
create policy "Users can update own profile display fields" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "Staff can update profile display fields" on public.profiles for update to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
revoke update on public.profiles from authenticated;
grant update (full_name, avatar_url) on public.profiles to authenticated;
drop policy if exists "clients_insert_policy" on public.clients;
drop policy if exists "clients_select_policy" on public.clients;
drop policy if exists "clients_update_policy" on public.clients;
drop policy if exists "Clients can view own client row" on public.clients;
drop policy if exists "Clients can update own client row" on public.clients;
drop policy if exists "Staff can manage clients" on public.clients;
create policy "Clients can view own client row" on public.clients for select to authenticated using (profile_id = auth.uid());
create policy "Clients can update own client row" on public.clients for update to authenticated using (profile_id = auth.uid()) with check (profile_id = auth.uid());
create policy "Staff can manage clients" on public.clients for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Users can insert their own feedback" on public.feedback;
drop policy if exists "Users can view their own feedback" on public.feedback;
drop policy if exists "Trainers can view all feedback" on public.feedback;
drop policy if exists "Trainers can update feedback status" on public.feedback;
drop policy if exists "Authenticated users can insert own feedback" on public.feedback;
drop policy if exists "Authenticated users can view own feedback" on public.feedback;
drop policy if exists "Staff can view feedback" on public.feedback;
drop policy if exists "Staff can update feedback" on public.feedback;
create policy "Authenticated users can insert own feedback" on public.feedback for insert to authenticated with check (user_id = auth.uid());
create policy "Authenticated users can view own feedback" on public.feedback for select to authenticated using (user_id = auth.uid());
create policy "Staff can view feedback" on public.feedback for select to authenticated using (public.app_is_staff());
create policy "Staff can update feedback" on public.feedback for update to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Users can view own notifications" on public.notifications;
drop policy if exists "Users can update own notifications" on public.notifications;
create policy "Users can view own notifications" on public.notifications for select to authenticated using (user_id = auth.uid());
create policy "Users can update own notifications" on public.notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "Clients can manage own weight logs" on public.client_weight_logs;
drop policy if exists "Clients can read own programs" on public.client_weight_logs;
drop policy if exists "Trainers can manage weight logs" on public.client_weight_logs;
drop policy if exists "Clients can manage own weight logs" on public.client_weight_logs;
drop policy if exists "Staff can manage weight logs" on public.client_weight_logs;
create policy "Clients can manage own weight logs" on public.client_weight_logs for all to authenticated using (public.app_owns_client(client_id)) with check (public.app_owns_client(client_id));
create policy "Staff can manage weight logs" on public.client_weight_logs for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can manage own measurement logs" on public.client_measurement_logs;
drop policy if exists "Trainers can manage measurement logs" on public.client_measurement_logs;
drop policy if exists "Staff can manage measurement logs" on public.client_measurement_logs;
create policy "Clients can manage own measurement logs" on public.client_measurement_logs for all to authenticated using (public.app_owns_client(client_id)) with check (public.app_owns_client(client_id));
create policy "Staff can manage measurement logs" on public.client_measurement_logs for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can manage own meal logs" on public.meal_logs;
drop policy if exists "Trainers can manage meal logs" on public.meal_logs;
drop policy if exists "Staff can manage meal logs" on public.meal_logs;
create policy "Clients can manage own meal logs" on public.meal_logs for all to authenticated using (public.app_owns_client(client_id)) with check (public.app_owns_client(client_id));
create policy "Staff can manage meal logs" on public.meal_logs for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can manage own custom meal logs" on public.custom_meal_logs;
drop policy if exists "Trainers can manage custom meal logs" on public.custom_meal_logs;
drop policy if exists "Staff can manage custom meal logs" on public.custom_meal_logs;
create policy "Clients can manage own custom meal logs" on public.custom_meal_logs for all to authenticated using (public.app_owns_client(client_id)) with check (public.app_owns_client(client_id));
create policy "Staff can manage custom meal logs" on public.custom_meal_logs for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can manage own meal plans" on public.meal_plans;
drop policy if exists "Trainers can manage meal plans" on public.meal_plans;
drop policy if exists "Staff can manage meal plans" on public.meal_plans;
create policy "Clients can manage own meal plans" on public.meal_plans for all to authenticated using (public.app_owns_client(client_id)) with check (public.app_owns_client(client_id));
create policy "Staff can manage meal plans" on public.meal_plans for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can insert own daily tracking" on public.daily_tracking;
drop policy if exists "Clients can update own daily tracking" on public.daily_tracking;
drop policy if exists "Clients can view own daily tracking" on public.daily_tracking;
drop policy if exists "Clients can manage own daily tracking" on public.daily_tracking;
drop policy if exists "Staff can manage daily tracking" on public.daily_tracking;
create policy "Clients can manage own daily tracking" on public.daily_tracking for all to authenticated using (public.app_owns_client(client_id)) with check (public.app_owns_client(client_id));
create policy "Staff can manage daily tracking" on public.daily_tracking for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can insert own workout progress" on public.workout_progress;
drop policy if exists "Clients can update own workout progress" on public.workout_progress;
drop policy if exists "Clients can view own workout progress" on public.workout_progress;
drop policy if exists "Trainers can view all workout progress" on public.workout_progress;
drop policy if exists "Clients can manage own workout progress" on public.workout_progress;
drop policy if exists "Staff can manage workout progress" on public.workout_progress;
create policy "Clients can manage own workout progress" on public.workout_progress for all to authenticated using (public.app_owns_client(client_id)) with check (public.app_owns_client(client_id));
create policy "Staff can manage workout progress" on public.workout_progress for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can delete own workout set logs" on public.workout_set_logs;
drop policy if exists "Clients can insert own workout set logs" on public.workout_set_logs;
drop policy if exists "Clients can update own workout set logs" on public.workout_set_logs;
drop policy if exists "Clients can view own workout set logs" on public.workout_set_logs;
drop policy if exists "Trainers can view all workout set logs" on public.workout_set_logs;
drop policy if exists "Clients can manage own workout set logs" on public.workout_set_logs;
drop policy if exists "Staff can manage workout set logs" on public.workout_set_logs;
create policy "Clients can manage own workout set logs" on public.workout_set_logs for all to authenticated using (public.app_owns_client(client_id)) with check (public.app_owns_client(client_id));
create policy "Staff can manage workout set logs" on public.workout_set_logs for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can delete own workout completions" on public.client_workout_completions;
drop policy if exists "Clients can insert own workout completions" on public.client_workout_completions;
drop policy if exists "Clients can read own workout completions" on public.client_workout_completions;
drop policy if exists "Clients can update own workout completions" on public.client_workout_completions;
drop policy if exists "Clients can manage own workout completions" on public.client_workout_completions;
drop policy if exists "Staff can manage workout completions" on public.client_workout_completions;
create policy "Clients can manage own workout completions" on public.client_workout_completions for all to authenticated using (public.app_owns_client(client_id)) with check (public.app_owns_client(client_id));
create policy "Staff can manage workout completions" on public.client_workout_completions for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can manage own set logs" on public.client_program_set_logs;
drop policy if exists "Trainers can manage client set logs" on public.client_program_set_logs;
drop policy if exists "Staff can manage client set logs" on public.client_program_set_logs;
create policy "Clients can manage own set logs" on public.client_program_set_logs for all to authenticated using (public.app_owns_client(client_id)) with check (public.app_owns_client(client_id));
create policy "Staff can manage client set logs" on public.client_program_set_logs for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can create own programs" on public.client_programs;
drop policy if exists "Clients can view own programs" on public.client_programs;
drop policy if exists "Trainers can manage client programs" on public.client_programs;
drop policy if exists "Clients can manage own client programs" on public.client_programs;
drop policy if exists "Staff can manage client programs" on public.client_programs;
create policy "Clients can manage own client programs" on public.client_programs for all to authenticated using (public.app_owns_client(client_id)) with check (public.app_owns_client(client_id));
create policy "Staff can manage client programs" on public.client_programs for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can create own program days" on public.client_program_days;
drop policy if exists "Clients can read own program days" on public.client_program_days;
drop policy if exists "Clients can view own program days" on public.client_program_days;
drop policy if exists "Trainers can manage client program days" on public.client_program_days;
drop policy if exists "Clients can manage own program days" on public.client_program_days;
drop policy if exists "Staff can manage client program days" on public.client_program_days;
create policy "Clients can manage own program days" on public.client_program_days for all to authenticated using ( exists ( select 1 from public.client_programs cp where cp.id = client_program_days.client_program_id and public.app_owns_client(cp.client_id) ) ) with check ( exists ( select 1 from public.client_programs cp where cp.id = client_program_days.client_program_id and public.app_owns_client(cp.client_id) ) );
create policy "Staff can manage client program days" on public.client_program_days for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can create own program exercises" on public.client_program_day_exercises;
drop policy if exists "Clients can read own program exercises" on public.client_program_day_exercises;
drop policy if exists "Clients can view own program exercises" on public.client_program_day_exercises;
drop policy if exists "Trainers can manage client program day exercises" on public.client_program_day_exercises;
drop policy if exists "Clients can manage own program exercises" on public.client_program_day_exercises;
drop policy if exists "Staff can manage client program day exercises" on public.client_program_day_exercises;
create policy "Clients can manage own program exercises" on public.client_program_day_exercises for all to authenticated using ( exists ( select 1 from public.client_program_days cpd join public.client_programs cp on cp.id = cpd.client_program_id where cpd.id = client_program_day_exercises.client_program_day_id and public.app_owns_client(cp.client_id) ) ) with check ( exists ( select 1 from public.client_program_days cpd join public.client_programs cp on cp.id = cpd.client_program_id where cpd.id = client_program_day_exercises.client_program_day_id and public.app_owns_client(cp.client_id) ) );
create policy "Staff can manage client program day exercises" on public.client_program_day_exercises for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Clients can read own messages" on public.client_messages;
drop policy if exists "Clients can send own messages" on public.client_messages;
drop policy if exists "Staff can read client messages" on public.client_messages;
drop policy if exists "Staff can reply to client messages" on public.client_messages;
drop policy if exists "Staff can update message read state" on public.client_messages;
create policy "Clients can read own messages" on public.client_messages for select to authenticated using (public.app_owns_client(client_id));
create policy "Clients can send own messages" on public.client_messages for insert to authenticated with check ( sender_role = 'client' and public.app_owns_client(client_id) );
create policy "Staff can read client messages" on public.client_messages for select to authenticated using (public.app_is_staff());
create policy "Staff can reply to client messages" on public.client_messages for insert to authenticated with check ( sender_role = 'trainer' and public.app_is_staff() );
create policy "Staff can update message read state" on public.client_messages for update to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
drop policy if exists "Anyone can view milestone configs" on public.milestone_config;
drop policy if exists "Trainers can manage milestone configs" on public.milestone_config;
create policy "Authenticated users can view milestone configs" on public.milestone_config for select to authenticated using (true);
create policy "Staff can manage milestone configs" on public.milestone_config for all to authenticated using (public.app_is_staff()) with check (public.app_is_staff());
